version: '3.8'

services:
  app:
    image: dylanckawalec/attestation-dashboard:latest
    container_name: tee-trust-validator
    
    # Port mapping for all services
    ports:
      - "3000:3000"  # NextJS Dashboard with Algorithm Visualizer
      - "8000:8000"  # Python API with real TEE data
      - "8001:8001"  # Bun Server for high-performance dStack ops
    
    # Critical TEE volume mounts (fixed for Phala environment)
    volumes:
      - /var/run/dstack.sock:/var/run/dstack.sock   # dStack 0.5.x socket
      - /var/run/tappd.sock:/var/run/tappd.sock     # dStack < 0.5.x compatibility
      - ./logs:/app/logs
    
    # Environment variables (injected by Phala CLI)
    environment:
      - PHALA_API_KEY
      - PHALA_ENDPOINT
      - PHALA_CLUSTER_ID
      - PHALA_CONTRACT_ID
      - APP_NAME
      - DEVELOPER_NAME
      - DEVELOPER_ROLE
      - ORGANIZATION
      - NODE_ENV
      - TEE_ENVIRONMENT
      - ENABLE_MOCK_MODE
      - REQUIRE_ATTESTATION
      - ATTESTATION_SEED
      - ATTESTATION_SALT
      - PORT
      - API_PORT
      - BUN_PORT
    
    # Network configuration
    networks:
      - tee-network
    
    # Run as nextjs user (matching Python dependencies installation)
    user: nextjs
    
    # Use default CMD from Dockerfile (supervisord)
    
    # Production restart policy
    restart: unless-stopped
    
    # Health check for all services
    healthcheck:
      test: |
        curl -f http://localhost:3000/ &&
        curl -f http://localhost:8000/ &&
        curl -f http://localhost:8001/
      interval: 60s
      timeout: 15s
      retries: 3
      start_period: 120s
    
    # Resource limits for TEE
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 2048M
        reservations:
          cpus: '1.0'
          memory: 1024M

# Network for TEE services
networks:
  tee-network:
    driver: bridge