version: '3.8'

services:
  app:
    image: dylanckawalec/attestation-dashboard:latest
    container_name: tee-trust-validator
    ports:
      - "3000:3000" # NextJS Dashboard
      - "8000:8000" # Python API
      - "8001:8001" # Bun Server (optional)
    volumes:
      - /var/run/tappd.sock:/var/run/tappd.sock  # TEE attestation socket
      - /var/run/dstack.sock:/var/run/dstack.sock # dStack socket
      - ./logs:/app/logs
    environment:
      # Phala TEE Configuration (injected by Phala CLI)
      PHALA_API_KEY: ${PHALA_API_KEY}
      PHALA_ENDPOINT: ${PHALA_ENDPOINT}
      PHALA_CLUSTER_ID: ${PHALA_CLUSTER_ID}
      PHALA_CONTRACT_ID: ${PHALA_CONTRACT_ID}
      
      # Application Identity
      APP_NAME: ${APP_NAME}
      DEVELOPER_NAME: ${DEVELOPER_NAME}
      DEVELOPER_ROLE: ${DEVELOPER_ROLE}
      ORGANIZATION: ${ORGANIZATION}
      
      # Runtime Configuration
      NODE_ENV: production
      TEE_ENVIRONMENT: production
      ENABLE_MOCK_MODE: "false"
      REQUIRE_ATTESTATION: "true"
      
      # Attestation Seeds
      ATTESTATION_SEED: ${ATTESTATION_SEED}
      ATTESTATION_SALT: ${ATTESTATION_SALT}
      
      # Service Ports
      PORT: "3000"
      API_PORT: "8000"
      BUN_PORT: "8001"
      
    restart: always
    
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    
    # Security options for TEE
    security_opt:
      - no-new-privileges:true
    
    # Resource limits
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2048M
        reservations:
          cpus: '1'
          memory: 1024M